FROM node:22-alpine

# Create app directory
WORKDIR /app

# Only copy what is strictly needed
COPY package.json ./
COPY index.js ./

# Install only production dependencies
RUN npm install --omit=dev

# Run the app
CMD ["node", "index.js"]
